# Starts the website and browserless simultaneously

version: '3.8'
services:
  curl:
    image: curlimages/curl
    volumes:
      - ../:/app
    depends_on:
      website:
        condition: service_healthy
      browserless:
        condition: service_healthy
    links:
      - browserless
    command: ["sh", "/app/scripts/execute-download-pdf.sh"]

  website:
    build:
      context: ../
      dockerfile: Dockerfile
    healthcheck:
      test: curl -f http://localhost:4000
    ports:
      - 4000:4000

  browserless:
    container_name: browserless
    image: browserless/chrome
    healthcheck:
      test: curl -f http://localhost:3000
    ports:
      - 3000:3000
    links:
      - website