# Starts the website and browserless simultaneously

version: '3.8'
services:
  curl:
    image: curlimages/curl
    # volumes:
    #   - ../:/app
    # depends_on:
    #   - website
    #   - browserless
    # links:
    #   - browserless
    # command:
    #   - ["curl", ""]

  website:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 4000:4000

  browserless:
    container_name: browserless
    image: browserless/chrome
    ports:
      - 3000:3000
    links:
      - website