on:
  push:
    branches:
      - master
    # paths:
    #   - resume.html

jobs:
  build_resume:
    runs-on: ubuntu-latest
    name: build-resume
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - name: Build and cache images
        run: |
          docker buildx create --use --driver=docker-container
          docker buildx bake -f docker/compose-resume.yml --set *.cache-to="type=gha,mode=max" --set *.cache-from="type=gha" --set *.context=. --load
      - name: Start containers
        run: docker-compose -f docker/compose-resume.yml up -d
      - name: Render and save PDF
        # 1. Grab code to download PDf file, escaping double quotes
        # 2. Make a request to our browserless/chrome container, storing the resulting PDF
        run: |
          code=$(cat scripts/download-pdf.js | sed 's/"/\\\"/g')
          echo "$code"
          curl http://localhost:3000
          curl browserless:3000
          curl -s -X POST -H "Content-Type: application/json" -d '{"code":"$code"}' browserless:3000/function -o resume.pdf
        # 1. Store the new resume in git history (hopefully triggers a new build of the GH page...)
      - name: Add PDF to git history
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add resume.pdf
          git commit -m "Automated commit to regenerate resume.pdf"
          git push
