on:
  push:
    branches:
      - master
    # paths:
    #   - resume.html

jobs:
  build_resume:
    runs-on: ubuntu-latest
    name: build-resume
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Expose GitHub Runtime
      #   uses: crazy-max/ghaction-github-runtime@v2
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # - name: Build and cache images
      #   uses: docker/bake-action@master
      #   with:
      #     load: true
      #     set: |
      #       *.cache-from="type=gha"
      #       *.cache-to="type=gha"
      #       *.context=.
      #     files: docker/compose-resume.yml
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build lualatex container
        uses: docker/build-push-action@v4
        with:
          context: ./docker/latex
          tags: tbrockman/lualatex
          file: ./docker/latex/Dockerfile
      - uses: addnab/docker-run-action@v3
        with:
          image: tbrockman/lualatex
          options: -v ${{ github.workspace }}/resume:/src -v ${{ github.workspace }}/_data:/data 
      - name: Test dir
        run: ls -l
      - name: Test dir
        run: ls -l ${{ github.workspace }}/resume
      # - name: Add PDF to git history
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add resume.pdf
      #     git commit -m "Automated commit to regenerate resume.pdf"
      #     git push
