on:
  push:
    branches:
      - master
    # paths:
    #   - resume.html

jobs:
  build_resume:
    runs-on: ubuntu-latest
    name: build-resume
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and cache images
        uses: docker/bake-action@master
        with:
          load: true
          set: |
            *.cache-from="type=gha"
            *.cache-to="type=gha"
            *.context=.
          files: docker/compose-resume.yml
      - name: Start containers
        run: docker-compose -f docker/compose-resume.yml up -d
      - name: Render and save PDF
        # 1. Grab code to download PDf file, escaping double quotes
        # 2. Make a request to our browserless/chrome container, storing the resulting PDF
        run: |
          code=$(cat scripts/download-pdf.js | sed 's/"/\\\"/g')
          echo "$code"
          docker run curlimages/curl -X POST -H "Content-Type: application/json" -d '{"code":"$code"}' browserless:3000/function > resume.pdf
          ls -l
        # 1. Store the new resume in git history (hopefully triggers a new build of the GH page...)
      - name: Add PDF to git history
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add resume.pdf
          git commit -m "Automated commit to regenerate resume.pdf"
          git push
