on:
    push:
        branches: [master]

jobs:
    build_resume:
        runs-on: ubuntu-latest
        name: build-resume
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Build Dockerfile
            - name: Start website container
            - name: Start browserless container
            - name: Render and save PDF
            - name: Add resulting PDF to git history
