on:
  push:
    branches:
      - master
    paths:
      - _posts/**
  workflow_dispatch:

jobs:
  create_issues:
    runs-on: ubuntu-latest
    name: create-issue-steps
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create issues
        uses: tbrockman/social-action@debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}